version: '3'
services:

  #PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: php:fpm
    container_name: example_project_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    depends_on:
    - web
    volumes:
    - ./:/var/www
    - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
    - php-network

  #Nginx Service
  web:
    image: nginx:alpine
    container_name: example_project_webserver
    restart: unless-stopped
    tty: true
    ports:
    - "2001:80"
    expose:
    - "2001"
    volumes:
    - ./:/var/www
    - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
    - php-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: example_project_db
    restart: unless-stopped
    tty: true
    ports:
    - "3302:3306"
    expose:
    - "3306"
    environment:
      MYSQL_DATABASE: example_project_local
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - dbdata:/var/lib/mysql/
    - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
    - php-network

#Docker Networks
networks:
  php-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
